### ISSUE TITLE
What about adding gzip?

### ISSUE THREAD

**Issue by mavnt** [alisinabh/paperify#14]
First of all, really nice idea :smile: .

So, since we're printing binary data, what about piping into gzip before splitting the file and after joining it?
I gave it a try and I don't see any issues with it.

:wave: :wave:  :wave:

**Comment by alisinabh** [comment]
The problem with gzip is it does not necessarily reduce the size of non text based files (Private keys, Binary data). Look at the below example.

```bash
> dd if=/dev/urandom bs=1 count=2953 2>/dev/null | gzip | wc -c
2976
```

It takes in 2953 bytes of arbitrary data and spits out 2976 bytes of data (adds 23 bytes) which can cause adding pages for small files like GPG key backups or small binary backups.

One solution to this is analyzing the size of gzipped file and use gzip only if the gzipped version is lighter. But using this we need to add some kind of flag to the start of the file so in `digitallify` step we can know if this file was compressed or not!

Please let me know what you think.

**Comment by mavnt** [comment]
Well, I guess that using a flag may be the right compromise. The flag may be at the start of the file like you suggested or could be explicitly passed as a command line argument (`docker run -v $(pwd):/target --entrypoint=/paperify/digitallify.sh alisinabh/paperify -d OUTPUT_FILE .`).

I don't know, maybe it's not worth it as one may just compress files beforehand.

**Comment by alisinabh** [comment]
Also another issue is that since this project has been released and many may have used it, I don't want to introduce any breaking changes. So any change that we want to make should not affect old backups. (e.g. Not being able to digitallify them without custom switches).

Actually I was thinking about making a wizard script so that people with less knowledge of unix can use that and in that wizard we can suggest to use gzip or add encryption to their backups. This way we can keep the `paperify.sh` and `digitallify.sh` minimal.

What do you think?

**Comment by mavnt** [comment]
Yes, I think that may be a good idea. I'm closing this issue then. :smile:
